module.exports = [
    {
        "Peak Name": "Smith Mountain",
        "Summit": "9,533 ",
        "Start": "8,395 ",
        "Mileage": "1.4",
        "Quad. Map": "Monache Mtn.",
        "Class": "2",
        "Gain": "995 ",
        "Section": "1.10",
        "Trail Head": "SNF 21S36",
        "Lat/Lon:": "36.12750°N / 118.20778°W",
        "Overview": "Smith Mountain is on the Kern Plateau, near Kennedy Meadows. The highpoint of about half dozen small peaks in the area surrounded by pine forests and lush meadows, Smith is probably the most climbed of the lot. The peak is mostly tree covered, but the summit is topped by a small granite formation that requires some class II scrambling on excellent rock covered with pretty lichen.",
        "Route": "From the parking area, walk up old logging road about 3/4 mile to where it crosses a motorcycle trail, Turn right and follow it a short distance (couple hundred yards), then leave the trail to the left and cross-country up the tree covered ridge of Smith Mountain. There are some cairns but no trail. It's an easy hike, about 3 miles roundtrip.",
        "Website": "https://www.summitpost.org/smith-mountain/206534",
        "Image": "https://sp-images.summitpost.org/206553.JPG?auto=format&fit=max&h=800&ixlib=php-2.1.1&q=35&s=7697e335c3973d91008d339260e43c29"
    },
    {
        "Peak Name": "English Mountain",
        "Summit": "8,373 ",
        "Start": "7,075 ",
        "Mileage": "1.9",
        "Quad. Map": "English Mtn.",
        "Class": "2",
        "Gain": "1,300 ",
        "Section": "24.6",
        "Trail Head": "Tollhouse Lake",
        "Lat/Lon:": "39.44630°N / 120.5512°W",
        "Overview": "Although modest in size, appearance and climbing challenges, English Mountain provides great views of the Northern Sierras. There are no maintained trails up English, but the landscape is a mix of open piney woods, low brush and boulder fields – you can walk almost anywhere you want.",
        "Route": "There are no maintained trails up English, but the landscape is a mix of open piney woods, low brush and boulder fields – you can walk almost anywhere you want.",
        "Website": "https://www.summitpost.org/english-mountain/907829",
        "Image": "https://sp-images.summitpost.org/907836.jpg?auto=format&fit=max&h=800&ixlib=php-2.1.1&q=35&s=49af388b030089217cf21a504cfbfc7c"
    },
    {
        "Peak Name": "Lamont Peak",
        "Summit": "7,429 ",
        "Start": "5,500 ",
        "Mileage": "1.9",
        "Quad. Map": "Lamont Peak",
        "Class": "2",
        "Gain": "2,560 ",
        "Loss": "330 ",
        "Section": "1.4",
        "Trail Head": "Lamont Peak Trail",
        "Lat/Lon:": "35.79200°N / 118.0436°W",
        "Overview": "Lamont Peak is the striking, pinnacled ridge just south of Lamont Meadows. Sometimes you have to wonder what people were thinking when naming peaks. Though I'm sure Mr. Lamont (I'm assuming it was named for a Mr. Lamont) lived a life worthy of recognition, it seems to me that his name should have been attached to nearby Sawtooth Peak, and the Sawtooth moniker given to this one. The named peak is not the highest point on the formation. This distinction belongs to either one of the pinnacles on the north ridge (don't ask me which one), or the high point on the ridge joining Lamont Peak with the the Sierra Crest, known informally as \"East Lamont Peak\". All of that notwithstanding, the Sierra Club summit register is on the named peak. It's a short, pleasant walk from Canebrake Road. On top, you are rewarded with a view of the Domelands Wilderness to the west, and the high meadows and rolling, pine-covered hills to the north and south.",
        "Route": "Lamont Peak Trailhead - By far the easiest way to do the peak. From the trailhead at the saddle on Canebrake Road, head east on the signed trail and follow it more or less straight up the ridge to the summit. This is not an engineered trail like the PCT. This old use trail contains only one token switchback. It can be hard to follow in places, but have faith, it is really does lead all the way to the summit area. If you think you've lost it, stop and backtrack a few yards and you're sure to pick it up again.",
        "Website": "https://www.summitpost.org/lamont-peak/190016",
        "Image": "https://sp-images.summitpost.org/190019.jpg?auto=format&fit=max&h=800&ixlib=php-2.1.1&q=35&s=f7e6d5af5c127d9707b18d64601e3da1"
    },
    {
        "Peak Name": "Independence Peak",
        "Summit": "11,742 ",
        "Start": "9,190 ",
        "Mileage": "2.0",
        "Quad. Map": "Kearsarge Peak",
        "Class": "3",
        "Gain": "2,595 ",
        "Loss": "45 ",
        "Section": "9.2",
        "Trail Head": "Robertson Lake Trail",
        "Lat/Lon:": "36.76100°N / 118.331°W",
        "Overview": "ndependence Peak is located in the Sierra Nevada mountains of California. It lies east of the Sierra Crest not far from the Onion Valley/Kearsarge pass Trailhead. This mountain is named for the town of Independence along the 395 in Owens Valley, and it is a striking site when viewed from town. Although it is a smaller mountain compared to it's neighbors, it is a fun class 3 climb that can be easily done in a day from Onion Valley. ",
        "Route": "Take the Onion Valley road out of the town of Indepedence along the 395 in Owen's Valley. Go for 14 miles to the hiker's parking area.",
        "Website": "https://www.summitpost.org/independence-peak/151875",
        "Image": "https://sp-images.summitpost.org/844146.jpg?auto=format&fit=max&h=800&ixlib=php-2.1.1&q=35&s=00daeac771599ae346d1fb1b07dab0dc"
    },
    {
        "Peak Name": "Taylor Dome",
        "Summit": "8,802 ",
        "Start": "7,830 ",
        "Mileage": "2.3",
        "Quad. Map": "Cannell Peak",
        "Class": "2s3",
        "Gain": "1,155 ",
        "Loss": "185 ",
        "Section": "1.7",
        "Trail Head": "Big Meadows Trail",
        "Lat/Lon:": "35.85630°N / 118.3033°W",
        "Overview": "Taylor Dome is one of many impressive granite domes found in Sequoia National Forest's Domeland Wilderness, and along with Rockhouse Peak and Pilot Knob (S) is one of three SPS listed peaks found in the wilderness. The peak is a short but enjoyable scramble, and can be easily climbed in a day with nearby Rockhouse Peak.",
        "Route": "The easiest route up the peak is likely the west ridge, which can be climbed from a saddle along the Taylor Meadow trail (Pass 8080+). This is all class 1-2 until the final summit block, which is easy third class. The summit block can also be reached easily from the north, from the Manter trail just west of Manter Meadow. It is possible to angle to the west for the usual class 2-3 route up the summit block, or one can climb the class 3-4 north face directly via a slightly awkward chimney and steep, easy face climbing (huge holds!).",
        "Website": "https://www.summitpost.org/taylor-dome/152728",
        "Image": "https://sp-images.summitpost.org/820590.JPG?auto=format&fit=max&h=800&ixlib=php-2.1.1&q=35&s=2ab88d7337a059b31cfda6b80444ba55"
    },
    {
        "Peak Name": "Dunderberg Peak",
        "Summit": "12,374 ",
        "Start": "9,810 ",
        "Mileage": "2.3",
        "Quad. Map": "Dunderberg Peak",
        "Class": "2",
        "Gain": "2,745 ",
        "Loss": "180 ",
        "Section": "22.5",
        "Trail Head": "Virginia Lakes Trail",
        "Lat/Lon:": "38.06500°N / 119.273°W",
        "Overview": "Dunderberg Peak is a large lump of rock east of the Sierra crest near the divide between the Owens and E. Walker Valleys (Conway Summit). Dunderberg Peak doesn't offer much excitement for the hard core mountaineer, but it has several strong points. First, it is close to a major roadway and serves as a great \"first summit\" for newbie peakbaggers. Second, the peak is located a fair distance off of the main crest, and this location offers unparalleled views for a mere twelve-thousand foot peak. Finally, Dunderberg is a world class ski mountain, with terrific descents off all of its sides. A spring corn skiing trip to the Virginia Lakes area will put a smile on any skiers face.",
        "Route": "South and West sides of the peak are accessed from the Virginia Lakes area. The east and north sides of the peak are accessed from Dunderberg Meadow Road, a dirt road that branches north off of the Virginia Lakes road near the base of the mountain.",
        "Website": "https://www.summitpost.org/dunderberg-peak/151617",
        "Image": "https://sp-images.summitpost.org/450220.JPG?auto=format&fit=max&h=800&ixlib=php-2.1.1&q=35&s=315343c3beacfc39e602cb23beec16f0"
    },
    {
        "Peak Name": "Cathedral Peak",
        "Summit": "10,911 ",
        "Start": "8,570 ",
        "Mileage": "2.9",
        "Quad. Map": "Tenaya Lake",
        "Class": "3s4",
        "Gain": "2,440 ",
        "Loss": "100 ",
        "Section": "21.1",
        "Trail Head": "Tuolumne Meadows",
        "Lat/Lon:": "37.84780°N / 119.4047°W",
        "Overview": "Cathedral Peak is an outstanding granite pinnacle in the Tuolumne Meadows area of Yosemite National Park. It looks good from all sides, has expansive views from its class 4 summit block, and the SE Buttress is considered a classic climbing route. John Muir made the first ascent of Cathedral Peak in 1869, possibly the first class 4 climb to be made anywhere in the Sierra.",
        "Route": "The SE Buttress is an extremely popular route among climbers despite the three mile approach hike, and there is often a line to climb it on weekends. Even during weekdays it is climbed by several parties each day during the summer months. The peak can be climbed without gear via the Mountaineers Route on the east side, or from the west side. The summit block is rated class 4, a moderate crack with excellent holds, and only about 15 feet high. ",
        "Website": "https://www.summitpost.org/cathedral-peak/150524",
        "Image": "https://sp-images.summitpost.org/295792.jpg?auto=format&fit=max&h=800&ixlib=php-2.1.1&q=35&s=2543f47aff97bba5eab36c264f30c71c"
    },
    {
        "Peak Name": "Adams Peak",
        "Summit": "8,197 ",
        "Start": "6,310 ",
        "Mileage": "3.0",
        "Quad. Map": "Constantia",
        "Class": "2",
        "Gain": "1,885 ",
        "Section": "24.9",
        "Trail Head": "Forest service road",
        "Lat/Lon:": "39.91060°N / 120.1003°W",
        "Overview": "Adams Peak is a seldom climbed peak in northeast California. It is ranked #128 on the California Prominence list with 2,197 ft of prominence. Adams Peak is located alongside US Hwy 395 between Susanville and Reno. ",
        "Route": "Adams Peak is a forested summit that rises above the arid desert area that extends from Reno all the way up to Susanville. The summit has great views in all directions. There is a Sierra Club register on the summit that dates back to the 1970’s. There aren’t a lot of signatures in the register for being there for almost 30 years.",
        "Website": "https://www.summitpost.org/adams-peak/230004",
        "Image": "https://sp-images.summitpost.org/913729.JPG?auto=format&fit=max&h=800&ixlib=php-2.1.1&q=35&s=6c4307b483bf145c92220591bea3067e"
    },
    {
        "Peak Name": "Round Top",
        "Summit": "10,381 ",
        "Start": "8,210 ",
        "Mileage": "3.1",
        "Quad. Map": "Carson Pass",
        "Class": "3",
        "Gain": "2,320 ",
        "Loss": "150 ",
        "Section": "23.7",
        "Trail Head": "Wood Lake Trail",
        "Lat/Lon:": "38.66360°N / 120.0003°W",
        "Overview": "Round Top is a prominent peak in the Tahoe region, one of three mountains (the other two are Freel Peak and Mount Rose) above 10,000 feet that are visible from Lake Tahoe. Its distinctive rounded summit of dark volcanic basalt towers above a beautiful alpine country that is rare in this part of Sierra Nevada.",
        "Route": " Its easiest route is class 2, although the summit block (the eastern crag) is rated class 3. On its north and east sides there are some challenging volcanic cliffs. The mountain is close enough to the road to do it on a moderate day hike",
        "Website": "https://www.summitpost.org/round-top/150503",
        "Image": "https://sp-images.summitpost.org/115449.jpg?auto=format&fit=max&h=800&ixlib=php-2.1.1&q=35&s=f262e7c33d8681ba47c20f0a369c512d"
    },
    {
        "Peak Name": "Mount Dana",
        "Summit": "13,057 ",
        "Start": "9,943 ",
        "Mileage": "3.1",
        "Quad. Map": "Mount Dana",
        "Class": "1",
        "Gain": "3,440 ",
        "Loss": "325 ",
        "Section": "21.8",
        "Trail Head": "Tioga Pass",
        "Lat/Lon:": "37.89970°N / 119.2203°W",
        "Overview": "Mount Dana sits on the eastern border of Yosemite National Park, astride the Sierra crest just south of Tioga Pass. It is the second highest peak in the park -- 51 feet higher than Kuna Peak, but 61 feet shy of Mount Lyell's glaciated summit. Many factors contribute to make Mount Dana a popular climbing destination for mountaineers of all strains. For one thing, it is very accessible: the mountain is adjacent to a major highway (CA 120), and although the peak is high, the trailhead is high also (~10,000 feet). It is also beautiful: the summit views are panoramic and quite impressive, with vistas of alpine glaciers, innumerable rugged peaks, sub-alpine meadows, high desert valleys and perhaps most interesting, Mono Lake.",
        "Route": "The easiest route to the summit is is the NW Slope (or West Slope) Route. This route starts at the Tioga Pass entrance station (9,941 ft; ca. 3000 meters), and is not technically difficult, but presents a reasonably strenuous half-day hike to the 13,053 ft summit.",
        "Website": "https://www.summitpost.org/mount-dana/150284",
        "Image": "https://sp-images.summitpost.org/945329.jpg?auto=format&fit=max&h=800&ixlib=php-2.1.1&q=35&s=51356787b0f0665b977e000271e6c100"
    },
    {
        "Peak Name": "Sierra Buttes",
        "Summit": "8,591 ",
        "Start": "6,230 ",
        "Mileage": "3.2",
        "Quad. Map": "Sierra City",
        "Class": "1",
        "Gain": "2,485 ",
        "Loss": "125 ",
        "Section": "24.7",
        "Trail Head": "Forest Route 93",
        "Lat/Lon:": "39.59360°N / 120.64°W",
        "Overview": "Sierra Buttes is the dominant peak in the Lakes Basin area of northern Sierra Nevada. There is nothing higher north until Lassen Peak and south until Mount Lola. It is a craggy peak of volcanic origin, with lots of spectacular pinnacles on top. The summit pinnacle is about 100 feet high and slightly overhanging, on top of which is a fire lookout hut perched precariously, with exhilarating exposure. However, with the aid of the steel staircases anyone can reach the top with no problem.",
        "Route": "Sierra Buttes has an easy hiking trail to reach the summit, yet its craggy cliffs offer technical rock climbing challenges. It also contains steep ski runs on several of its flanks.",
        "Website": "https://www.summitpost.org/sierra-buttes/150520",
        "Image": "https://sp-images.summitpost.org/936467.jpg?auto=format&fit=max&h=800&ixlib=php-2.1.1&q=35&s=b4e62b4535a2e8d3b4962c843427f5b2"
    },
    {
        "Peak Name": "Kearsarge Peak",
        "Summit": "12,618 ",
        "Start": "8,955 ",
        "Mileage": "3.2",
        "Quad. Map": "Kearsarge Peak",
        "Class": "1",
        "Gain": "3,855 ",
        "Loss": "190 ",
        "Section": "9.3",
        "Trail Head": "Old mining trail",
        "Lat/Lon:": "36.78900°N / 118.346°W",
        "Overview": "Kearsarge Peak is located in the Sierra Nevada mountains of California. It lies east of the Sierra Crest not far from the Onion Valley/Kearsarge pass Trailhead, which is out of the town of Independence along the 395 highway. It's right at the edge of Owen's Valley, so there are pretty dramatic views up and down the valley. From certain angles, this mountain can resemble a pyramid when viewing from Owen's Valley. The view definitely makes you want to climb it!",
        "Route": "This is an easy peak to climb with great views. It can be done in a day from the hiker parking at Onion Valley.",
        "Website": "https://www.summitpost.org/kearsarge-peak/151874",
        "Image": "https://sp-images.summitpost.org/502633.JPG?auto=format&fit=max&h=800&ixlib=php-2.1.1&q=35&s=94af28931bcc0911f46327859d5f6dd5"
    },
    {
        "Peak Name": "Sirretta Peak",
        "Summit": "9,977 ",
        "Start": "7,830 ",
        "Mileage": "3.3",
        "Quad. Map": "Sirretta Peak",
        "Class": "1",
        "Gain": "2,215 ",
        "Loss": "70 ",
        "Section": "1.8",
        "Trail Head": "Cannell Meadows Trail 33E22",
        "Lat/Lon:": "35.92432°N / 118.33315°W",
        "Overview": "Sirretta Peak is most commonly hiked from the trail that also bears its name. The trail starts out as Cannell Meadow Trail (33E32). In 0.5 of a mile the trail branches right and turns into Sirretta trail heading North towards Sirretta Pass. ",
        "Route": "As you near the top of the pass you should leave the trail near waypoint 11S 0380227E 3976516N and turn sharply up hill to the West. Proceed on a bearing of 257° TN making your way up the slope through the Manzanita and rocks. Once you reach the ridge you will see the summit block and it should only be a short scramble to the top. Once at the top you will be rewarded with views of Big Meadow and the Domeland Wilderness.",
        "Website": "https://www.summitpost.org/sirretta-peak/515913",
        "Image": "https://sp-images.summitpost.org/515927.JPG?auto=format&fit=max&h=800&ixlib=php-2.1.1&q=35&s=a6caa83b9f22bd9fd981f9eaf8ba7e43"
    },
    {
        "Peak Name": "Mount Conness",
        "Summit": "12,590 ",
        "Start": "10,100 ",
        "Mileage": "3.3",
        "Quad. Map": "Tioga Pass",
        "Class": "2",
        "Gain": "2,860 ",
        "Loss": "370 ",
        "Section": "22.2",
        "Trail Head": "Saddlebag Lake",
        "Lat/Lon:": "37.96720°N / 119.3192°W",
        "Overview": "Mount Conness is the highest peak in Sierra Nevada north of Tioga Pass Road (Highway 120). It is a prominent peak on the eastern boundary of Yosemite National Park, whose vertical southwest wall (one of the best spots for big wall climbing in the Tuolumne Meadows area) is visible from many points on Tioga Pass Road (Hwy-120).",
        "Route": "The summit of Mount Conness is class 2 from Young Lakes on the west side (easiest route), which requires a long approach from Tuolumne Meadows trailhead in Yosemite National Park. The east side approach is shorter but a bit more difficult. Mount Conness offers challenging technical rock routes on its north ridge and southwest wall. Nearby North Peak has two steep couloirs popular for ice-climbing. For those interested in less technical scrambles, Mount Conness crest area is paradise. The relatively gentle terrain, clean granite and lack of vegetation make for many thrilling off-trail routes.",
        "Website": "https://www.summitpost.org/mount-conness/150473",
        "Image": "https://sp-images.summitpost.org/83933.JPG?auto=format&fit=max&h=800&ixlib=php-2.1.1&q=35&s=5176992149d3bdcb8474969b1e98064a"
    },
    {
        "Peak Name": "Mount Elwell",
        "Summit": "7,818 ",
        "Start": "6,560 ",
        "Mileage": "3.4",
        "Quad. Map": "Gold Lake",
        "Class": "1",
        "Gain": "2,080 ",
        "Loss": "820 ",
        "Section": "24.8",
        "Trail Head": "Lake Basin campground",
        "Lat/Lon:": "39.70840°N / 120.6881°W",
        "Overview": "Mount Elwell, one of the most northern Sierra Peaks Section (SPS) peaks, resides on the border of Plumas and Sierra Counties in Plumas National Forest. Though the summit is tame by most standards, the summit provides an exceptional view of the Lakes Basin below it, as well as views of Sierra Buttes, Weber Peak, and the Bald Mountain Range/Sardine Peak to the South/SE; Mt. Lassen can also be seen to the NW on a clear day.",
        "Route": "From the parking lot at Elwell Lodge, take the \"Silver Lake\" Trail. This trail later forks, take the \"Long Lake\" fork. It will fork yet again, take the \"Long Lake Trail\", which is not on the Topo. This trail follows the east side of Long Lake and connects with the Trail that runs along the base of Elwell. When I hiked this Trail, there was a log blocking the beginning of it, apparently placed by the Forest Service. This trail is not damaged or difficult to follow; it may be difficult to follow in the winter though, so if you are doing it then, I suggest bringing a GPS because you cannot see the lake most of the time. Once you've crossed the dam, head NW until you connect with the summit trail; follow this trail to the summit.",
        "Website": "https://www.summitpost.org/mount-elwell/297105",
        "Image": "https://sp-images.summitpost.org/297139.jpg?auto=format&fit=max&h=800&ixlib=php-2.1.1&q=35&s=060f1faa58a7dba568d52b7d39e85168"
    },
    {
        "Peak Name": "Mount Gibbs",
        "Summit": "12,773 ",
        "Start": "9,689 ",
        "Mileage": "3.5",
        "Quad. Map": "Mount Dana",
        "Class": "1",
        "Gain": "3,195 ",
        "Loss": "110 ",
        "Section": "21.7",
        "Trail Head": "Mono Pass Trail",
        "Lat/Lon:": "37.87720°N / 119.211°W",
        "Overview": "Mount Gibbs is located close to Mount Dana near Tioga Pass in Yosemite National Park. While Mount Dana sees a lot of visitors due to the easy access and its position as the second highest peak in the park, only a fraction of the Dana visitors continue on to Gibbs. It is an easy mountain to climb and the views from the top are spectacular.",
        "Route": "In order to climb Mount Gibbs in cominbation with Mount Dana, start out from the Yosemite entrance station near Tioga Pass (see Mount Dana section for detail). From the summit of Dana, descend the southeast side to the saddle in between Dana and Gibbs near the top of the Dana Couloir. Then head South on the talus to get to the fractured ridge (heading southwest) leading up to the summit. The last section of the ridge is a fun class 2-3 scramble. A different approach to Gibbs is to follow the pack trail from highway 120 towards Mono Pass. (The trailhead is approximately 1.5 miles west from Tioga Pass). However, before you get to the pass, leave the trail and head east up the more compact talus towards the summit of Gibbs.",
        "Website": "https://www.summitpost.org/mount-gibbs/154415",
        "Image": "https://sp-images.summitpost.org/119496.jpg?auto=format&fit=max&h=800&ixlib=php-2.1.1&q=35&s=2f64a75a017a1d017678885d4bd1d6aa"
    },
    {
        "Peak Name": "Owens Peak",
        "Summit": "8,453 ",
        "Start": "5,400 ",
        "Mileage": "3.5",
        "Quad. Map": "Owens Peak",
        "Class": "2",
        "Gain": "3,200 ",
        "Loss": "145 ",
        "Section": "1.2",
        "Trail Head": "Indian Wells Canyon",
        "Lat/Lon:": "35.73800°N / 117.996°W",
        "Overview": "This mountain stands as the most dominant peak in the Southern Sierra area right outside the towns of Ridgecrest and Inyokern. ",
        "Route": "The hike up to the summit is short but intense, gaining around 2850 feet in around 2 miles. The views from the top are impressive. Telescope peak can be seen to the east, Mt Whitney, Langley and Olancha to the north, Lake Isabella to the west, and desert views all around you. The route up is mostly a hike, but does involve scrambling on some class 2 granite slabs and one short boulder hop before that.",
        "Website": "https://www.summitpost.org/owens-peak/154143",
        "Image": "https://sp-images.summitpost.org/107417.JPG?auto=format&fit=max&h=800&ixlib=php-2.1.1&q=35&s=b1b2cf76cf806af0691e07bc9358f672"
    },
    {
        "Peak Name": "Dragon Peak",
        "Summit": "12,927+",
        "Start": "9,185 ",
        "Mileage": "3.5",
        "Quad. Map": "Kearsarge Peak",
        "Class": "3s4",
        "Gain": "4,020 ",
        "Loss": "280 ",
        "Section": "9.10",
        "Trail Head": "Golden Trout Lakes Trail",
        "Lat/Lon:": "36.79010°N / 118.3758°W",
        "Overview": "Dragon Peak beckons to the climber as the distinctive pyramid seen from the Golden Trout Lakes drainage, accompanied just to the north by the dramatic \"Dragons Tooth\". Dragon Peaks' somewhat challenging third class summit blocks and wonderful vistas have garnered it a spot on the Sierra Club SPS list. On first sight from the lower lakes it begs you to come on up - it's why we climb!",
        "Route": "The peak can be reached from a few different directions, the southeast ridge route from Onion Valley apparently being the most traveled (coincidentally this is the easiest and most direct approach.) It can also be reached via a third class traverse from Mt Gould which lies approximately 1 mile to the south along the Sierra Crest and at least one 5th class route has been documented. Undoubtedly many other approaches exist. Be aware that there is much loose rock on this route.",
        "Website": "https://www.summitpost.org/dragon-peak/152723",
        "Image": "https://sp-images.summitpost.org/275026.jpg?auto=format&fit=max&h=800&ixlib=php-2.1.1&q=35&s=d34f5752d1972ef1156975166491beda"
    },
    {
        "Peak Name": "Mount Warren",
        "Summit": "12,327 ",
        "Start": "7,815 ",
        "Mileage": "3.5",
        "Quad. Map": "Mount Dana",
        "Class": "1",
        "Gain": "4,515 ",
        "Section": "22.1",
        "Trail Head": "Lundy Lake",
        "Lat/Lon:": "37.98980°N / 119.2235°W",
        "Overview": "Mount Warren rises high above Mono Lake and stands as the gatekeeper to the eastern edge of Yosemite National Park.  The mountain itself is located to the east of the YNP boundary.   Instead, Mount Warrent is considered part of the Hoover Wilderness in the Inyo National Forest.",
        "Route": "Mount Warren ranks at #162 on the California top prominence peaks with 2,007 ft of prominence. Via the shortest route from Highway 120, there is a trail only about ¼ of the way to the summit and then it is a Class 2 scramble from there.  A hike from Lundy Canyon has a longer approach trail, but eventually leaves the large majority of the hike to route-finding and a Class 2 scramble.",
        "Website": "https://www.summitpost.org/mount-warren/339640",
        "Image": "https://sp-images.summitpost.org/792569.JPG?auto=format&fit=max&ixlib=php-2.1.1&q=35&w=500&s=f09647824bfc3e6d52fa8ad0ed13bcd3"
    },
    {
        "Peak Name": "Moses Mountain",
        "Summit": "9,331 ",
        "Start": "5,920 ",
        "Mileage": "3.7",
        "Quad. Map": "Moses Mountain",
        "Class": "3",
        "Gain": "3,510 ",
        "Loss": "100 ",
        "Section": "2.5",
        "Trail Head": "Long Meadow Trail",
        "Lat/Lon:": "36.27810°N / 118.679°W",
        "Overview": "This is a fun class 3 scramble of an SPS peak the Western Sierra. This peak can be done in a dayhike from the Hidden Falls Campground or a nice two day trip including N. Maggie Mountain.",
        "Route": "From the Hidden Falls Campgound cross the Tule River on a road, look for the River Trail sign on your left. Take the river trail north to meet up with the Summit Lake trail on the east side of the river. There is a good established campsite in Long Meadow. Long meadow is about 2-3 miles from the trailhead. The peak is about another 2-3 miles, depending on how you decide to go in order to avoid the brush. Total gain from the trailhead is about 3000 ft.",
        "Website": "https://www.summitpost.org/moses-mountain/154799",
        "Image": "https://sp-images.summitpost.org/899686.jpg?auto=format&fit=max&h=800&ixlib=php-2.1.1&q=35&s=2581f4169d1dc7dcf1231f0ba9c3ebc3"
    },
    {
        "Peak Name": "Pilot Knob (S)",
        "Summit": "6,200+",
        "Start": "2,710 ",
        "Mileage": "3.7",
        "Quad. Map": "Onyx",
        "Class": "2",
        "Gain": "3,610 ",
        "Loss": "120 ",
        "Section": "1.1",
        "Trail Head": "Dirt road",
        "Lat/Lon:": "37.27348°N / 118.75728°W",
        "Overview": "Pilot Knob is not one of those peaks that you climb as a noteworthy mountaineering objective; rather it is an isolated rise at the edge of a large plateau in the heart of the Sierra Nevada, a short distance north of Kings Canyon National Park. It is both the journey and Pilot Knob’s open location that make a visit here worthwhile. The views throughout your trip will be superb, regardless of the conditions, and the scene from the summit is just as fantastic. From the highpoint you are literally surrounded by imposing peaks in every direction.",
        "Route": "Pilot Knob is almost always ascended from the saddle east of the summit via either Humphreys Basin or the lakes north of the peak above French Canyon. The routes are both straightforward with mostly trail or very easy cross-country terrain, and offer outstanding scenery for the modest effort required in getting there.",
        "Website": "https://www.summitpost.org/pilot-knob/736249",
        "Image": "https://sp-images.summitpost.org/736154.JPG?auto=format&fit=max&h=800&ixlib=php-2.1.1&q=35&s=f3f30753dbea447729a5e3eba5f06689"
    },
    {
        "Peak Name": "University Peak",
        "Summit": "13,589 ",
        "Start": "9,200 ",
        "Mileage": "3.9",
        "Quad. Map": "Mount Williamson",
        "Class": "2",
        "Gain": "4,540 ",
        "Loss": "150 ",
        "Section": "9.1",
        "Trail Head": "Kearsarge Pass Trail",
        "Lat/Lon:": "36.74750°N / 118.3604°W",
        "Overview": "University Peak is a wonderful dayhike and climb and is easily accessed from Onion Valley, a popular eastside Sierra trailhead. It is set in a very beautiful part of the Sierra Wilderness. University Peak straddles the border between Kings Canyon National Park and the John Muir Wilderness in Inyo National Forest. It is big... 13,589 feet... the biggest peak and a prominent feature near Kearsarge Pass, and beautiful with many graceful and interesting features.",
        "Route": "Though there is only one commonly used trailhead to access University Peak there are two likely approaches. If targeting a route on the north side visitors use the Kearsarge Pass trail (typically leaving the trail in the vicinity of Gilbert Lake). Routes on the south and east aspects are approached via the Robinson Lake trail. The peak has moderate routes on both sides and a nice loop is possible.",
        "Website": "https://www.summitpost.org/university-peak/151291",
        "Image": "https://sp-images.summitpost.org/753959.jpg?auto=format&fit=max&h=800&ixlib=php-2.1.1&q=35&s=4e92471e9913581ccc5f7e6d5c7f337d"
    },
    {
        "Peak Name": "Mount Morrison",
        "Summit": "12,277 ",
        "Start": "7,645 ",
        "Mileage": "4.0",
        "Quad. Map": "Convict Lake",
        "Class": "2",
        "Gain": "4,870 ",
        "Loss": "240 ",
        "Section": "18.8",
        "Trail Head": "Convict Lake",
        "Lat/Lon:": "37.56170°N / 118.8589°W",
        "Overview": "Mt. Morrison is one of the more notable mountains in the Mammoth Lakes area of the Sierra Nevada.  Its North Face is a spectacular sight when viewed from US395 near the Mammoth airport.  The rock in this area is noted for it's superb coloring in shades of white, yellow, orange, red, and brown.  Mt. Morrison's summit pendant, a lower Paleozoic roof pendant (USGS Professional Paper 1145), is composed of Dolomite and Marble - basically metamorphosed limestone.  The age is Pre-cambrian making it some of the oldest rock in the Sierra.",
        "Route": " There are no trailheads to Mt. Morrison.  Easiest access is from Convict Lake which lies below the north side, and can be reached from US395 via the Convict Lake Rd, just south of the Mammoth airport. Convict Canyon, and the western aspects of Mt. Morrison are accessed via the Convict Creek Trail.  This trail is not in good shape, with many portions washed out in 2012.  The Mt. Laurel trail is suggested as an alternate until trail repairs/rebuild can be completed.",
        "Website": "https://www.summitpost.org/mount-morrison/150531",
        "Image": "https://sp-images.summitpost.org/471013.JPG?auto=format&fit=max&h=800&ixlib=php-2.1.1&q=35&s=e063d34fae779e9c0bc356c569b65417"
    },
    {
        "Peak Name": "Sawtooth Peak (S)",
        "Summit": "8,000+",
        "Start": "5,555 ",
        "Mileage": "4.1",
        "Quad. Map": "Nine Mile Canyon",
        "Class": "2",
        "Gain": "2,445 ",
        "Section": "1.5",
        "Trail Head": "Pacific Crest Trail",
        "Lat/Lon:": "36.45400°N / 118.554°W",
        "Overview": "The best part about Sawtooth is the grand view of the Great Western Divide. The view of Monarch Lakes and the diverse choices you can take after summiting. An easy Class 2 climb, especially for the Sierras. ",
        "Route": "From Timber Gap trailhead take the trail up the east slopes of Mineral King Valley, then follow sign for Sawtooth Pass. One-way distance is 5 miles to Sawtooth Pass. From the pass, following the ridge to the south for an additional 1 mile of class 2 scrambling to reach the summit. According to scottyb for about 1/2 mile below Sawtooth Pass the trail climbs much steep sand, the main unpleasant part of the hike. It can possibly be avoided by going cross-country on the right, ascending the southwest ridge of Sawtooth Peak.",
        "Website": "https://www.summitpost.org/sawtooth-peak/151060",
        "Image": "https://sp-images.summitpost.org/23787.jpg?auto=format&fit=max&h=800&ixlib=php-2.1.1&q=35&s=33300f733095225dbb4ef8f308b2ce0e"
    },
    {
        "Peak Name": "Castle Peak",
        "Summit": "9,103 ",
        "Start": "7,230 ",
        "Mileage": "4.2",
        "Quad. Map": "Nordon",
        "Class": "1s3",
        "Gain": "2,235 ",
        "Loss": "360 ",
        "Section": "24.3",
        "Trail Head": "Boreal Ridge Parking",
        "Lat/Lon:": "39.36526°N / 120.3493°W",
        "Overview": "Castle Peak is one of the most popular hiking destinations in the Lake Tahoe Basin.  Castle Peak is the throat of an ancient volcano and its three turrets are easily visible form nearby Interstate 80. Castle Peak feels like a much higher mountain.  Its towering rocky summits are not unlike the rock towers found further south in the Sierra Nevada Range.",
        "Route": "What makes Castle Peak interesting is the summit itself.  Most people opt not to go to the true summit.  The West summit is the first one reached and only several feet lower than the true summit.  The true summit requires some steep scrambling down and then up to reach it.  Then, the summit is reached via a Class 3 scramble not for those with fear of heights.",
        "Website": "https://www.summitpost.org/castle-peak/152352",
        "Image": "https://sp-images.summitpost.org/329264.jpg?auto=format&fit=max&h=800&ixlib=php-2.1.1&q=35&s=185c8f34a2e6d04d0c87ef7ce8f76d37"
    },
    {
        "Peak Name": "North Peak",
        "Summit": "12,242 ",
        "Start": "10,100 ",
        "Mileage": "4.2",
        "Quad. Map": "Tioga Pass",
        "Class": "2",
        "Gain": "2,630 ",
        "Loss": "490 ",
        "Section": "22.3",
        "Trail Head": "Saddlebag Lake",
        "Lat/Lon:": "37.98250°N / 119.3128°W",
        "Overview": "For alpine routes in the Sierra Nevada, North Peak's accessibility from the road makes this a popular peak for climbing ice couloirs. It is easily reached in a few hours from the trailhead and is known as one of the most prestine areas in the Sierra Range. The approach is easy as compared to most other ice climbs in the area, the climbing is enjoyable and never too severe and it can be linked with Mt Conness' North Ridge to make for a spectacular traverse.",
        "Route": "Other less technical routes, such as the Southeast Chute, the Southwest Face and the Northwest Ridge allow hikers and climbers of all skill levels to also enjoy this peak. Spring skiing is also popular on the slopes and chutes of North Peak, as well as those on nearby Mount Conness and the Conness Glacier.",
        "Website": "https://www.summitpost.org/north-peak/150613",
        "Image": "https://sp-images.summitpost.org/321929.jpg?auto=format&fit=max&h=800&ixlib=php-2.1.1&q=35&s=cd0def354f7f28a4577cdd59a392aac7"
    },
    {
        "Peak Name": "Stanislaus Peak",
        "Summit": "11,233 ",
        "Start": "9,420 ",
        "Mileage": "4.2",
        "Quad. Map": "Disaster Peak",
        "Class": "1",
        "Gain": "2,570 ",
        "Loss": "755 ",
        "Section": "23.3",
        "Trail Head": "St. Mary's Pass Trail",
        "Lat/Lon:": "38.38420°N / 119.6661°W",
        "Overview": "Stanislaus Peak is a symmetrically round, flat topped peak located near Sonora Pass on California State Route 108, one of the Trans-Sierra routes that is closed during the winter. There are a couple of 11,000 ft. peaks in the area that can be summited in a day or less with Leavitt Peak to the south the highest. Stanislaus is a red colored ancient volcanic cone located north of Sonora Pass in the Carson - Iceberg Wilderness and is a sharp landmark for those traveling the Pacific Crest Trail. ",
        "Route": "The summit is very flat and covered with flat rocks that reminds one of roof tiles both by look and the clinky sound they make as you walk on them. This is an easy class 2 non-technical climb that can be combined with Sonora Peak to the south for a nice day of hiking. Do not be surprised by men in uniform. This area is used by the United States Marine Corps for mountain warfare training. The main base is about 10 miles east of Sonora Pass on State Route 108. From Stanislaus Peak one can see Round Top and Highland Peak to the north, Leavitt Peak and the Emigrant Wilderness to the south, and the Dardanelle Cones to the west.",
        "Website": "https://www.summitpost.org/stanislaus-peak/150594",
        "Image": "https://sp-images.summitpost.org/543900.JPG?auto=format&fit=max&h=800&ixlib=php-2.1.1&q=35&s=89d4294dc3f7dfe356c6af02068a6ab4"
    },
    {
        "Peak Name": "Mount Carillion",
        "Summit": "13,517+",
        "Start": "8,300 ",
        "Mileage": "4.2",
        "Quad. Map": "Mount Whitney",
        "Class": "2",
        "Gain": "5,465 ",
        "Loss": "250 ",
        "Section": "5.4",
        "Trail Head": "Mount Whitney Trail",
        "Lat/Lon:": "36.59270°N / 118.2778°W",
        "Overview": "Mt. Carillon is the peak just east of Mt. Russell, and about 500' shorter. The East Face routes are steep and seldom climbed, although there has been recent new route activity.",
        "Route": "Most summiters of Carillon ascend the South Slope routes, which are 2nd-to-easy 3rd class. Not surprisingly, Norman Clyde has the 1st ascent of this peak way back in 1925.",
        "Website": "https://www.summitpost.org/mount-carillon/151455",
        "Image": "https://sp-images.summitpost.org/768636.jpg?auto=format&fit=max&h=800&ixlib=php-2.1.1&q=35&s=2ebc427eda1519f0a22a5ff35206b5d7"
    },
    {
        "Peak Name": "North Maggie Mountain",
        "Summit": "10,234 ",
        "Start": "5,920 ",
        "Mileage": "4.3",
        "Quad. Map": "Moses Mountain",
        "Class": "1",
        "Gain": "4,315 ",
        "Section": "2.4",
        "Trail Head": "Shakes Camp",
        "Lat/Lon:": "36.27670°N / 118.638°W",
        "Overview": "This is a nice 2nd class SPS peak in the Western Sierra. A very fun two day trip when climbed with Moses Mountain or a good dayhike from the Hidden Falls Campground.",
        "Route": "Head north on the Summit Lake Trail to approach this peak. Then, chose to take the ridge or gully after leaving the trail and crossing the river. Whichever route looks less brushy should work out.",
        "Website": "https://www.summitpost.org/north-maggie-mountain/154800",
        "Image": "https://sp-images.summitpost.org/848663.JPG?auto=format&fit=max&h=800&ixlib=php-2.1.1&q=35&s=f6fb6ac4ceb48c55bff334402153f81b"
    },
    {
        "Peak Name": "Mount Russell",
        "Summit": "14,088 ",
        "Start": "8,300 ",
        "Mileage": "4.5",
        "Quad. Map": "Mount Whitney",
        "Class": "3",
        "Gain": "6,100 ",
        "Loss": "310 ",
        "Section": "5.3",
        "Trail Head": "Mount Whitney Trail",
        "Lat/Lon:": "36.59080°N / 118.2878°W",
        "Overview": "Mt. Russell lies a mile north of its much more famous neighbor, Mt. Whitney. Overshadowed by Mt. Whitney's additional 400 feet which makes it the tallest in the contiguous US, Mt. Russell receives only a fraction of the visitors. As one of the fifteen California 14ers, Mt. Russell hardly suffers from neglect, however, and its excellent rock climbing and the relative difficulty of the easiest routes makes it a favorite among mountaineers.",
        "Route": "The west and southwest faces feature sheer walls that rival those found on Whitney's East Face. There are various class 3-4 routes on the south, east, and north sides of the peak. The summit is a knife-edge with two high points on either end. The western point is the higher one.",
        "Website": "https://www.summitpost.org/mount-russell/150515",
        "Image": "https://sp-images.summitpost.org/86865.jpg?auto=format&fit=max&h=800&ixlib=php-2.1.1&q=35&s=78d7f19ccc1480f365b010a007ea3331"
    },
    {
        "Peak Name": "Mount Tallac",
        "Summit": "9,735 ",
        "Start": "6,440 ",
        "Mileage": "4.6",
        "Quad. Map": "Emerald Bay",
        "Class": "1",
        "Gain": "3,295 ",
        "Loss": "65 ",
        "Section": "23.11",
        "Trail Head": "Mount Tallac Trail",
        "Lat/Lon:": "38.90610°N / 120.10003°W",
        "Overview": "Mount Tallac is probably the most recognizable of the Tahoe Area peaks. With its distinctive \"cross\" of snow rising directly above the southwest corner of Lake Tahoe, Mount Tallac commands attention. While neither the highest peak in the area nor the hardest to summit, Mount Tallac nonetheless serves up enough adventure to satisfy nearly everyone.",
        "Route": "Mount Tallac (Cathedral Lake) Trail - In some circles, this is the \"official\" summer trail up Mount Tallac. Shorter (4.99 miles) than the Glen Alpine Trail, with equally beautiful views of Fallen Leaf Lake and Lake Tahoe on the ascent.",
        "Website": "https://www.summitpost.org/mount-tallac/150430",
        "Image": "https://sp-images.summitpost.org/632965.JPG?auto=format&fit=max&h=800&ixlib=php-2.1.1&q=35&s=b8bf4b68046174061f4fa370a11c9c1a"
    },
    {
        "Peak Name": "Excelsior Mountain",
        "Summit": "12,446 ",
        "Start": "9,810 ",
        "Mileage": "4.6",
        "Quad. Map": "Dunderberg Peak",
        "Class": "1",
        "Gain": "2,995 ",
        "Loss": "360 ",
        "Section": "22.4",
        "Trail Head": "Virginia Lakes Trail",
        "Lat/Lon:": "38.02400°N / 119.304°W",
        "Overview": "Excelsior Mountain is the next highest peak on the Sierra Nevada crest north of Mount Conness, on the northeastern border of Yosemite National Park. Excelsior's summit offers excellent views of North Peak, and Mount Conness and is a popular ski mountaineering destination.",
        "Route": "Excelsior Mountain features moderate backcountry skiing terrain on its summit ridge and northeast ridge as well as expert chutes. In spring when the access road is plowed Excelsior is only ~4.5 miles (hgrapid) one way from Virginia Lakes Trailhead, ideal for moderate level ski touring. Excelsior is also often skied from the south via Saddlebag Lake.",
        "Website": "https://www.summitpost.org/excelsior-mountain/150988",
        "Image": "https://sp-images.summitpost.org/56959.JPG?auto=format&fit=max&h=800&ixlib=php-2.1.1&q=35&s=845690e4c5d0aaa9b40070c9ce5ebf51"
    },
    {
        "Peak Name": "Mount Lola",
        "Summit": "9,148 ",
        "Start": "8,000 ",
        "Mileage": "4.8",
        "Quad. Map": "Indepence Lk.",
        "Class": "1",
        "Gain": "1,405 ",
        "Loss": "255 ",
        "Section": "24.5",
        "Trail Head": "Mt Lola Trail",
        "Lat/Lon:": "39.43300°N / 120.3641°W",
        "Overview": "Formed from an ancient volcano, Mt. Lola is a surprisingly unassuming mountain, even for the northern Sierra. Most of its sides are rounded and easily climbed, and it is outflanked by the more rugged features of its neighbors, Castle Peak to the south and Sierra Buttes to the northwest. But for a nondescript mountain it offers possibly the finest views of the northern Sierra region from its northern edge where the range melds into the Cascade Range (Mt. Lassen can be seen from the summit on a clear day) south to the Desolation Wilderness on the southwest edge of Lake Tahoe.",
        "Route": "The peak is not a difficult climb, requiring only 10mi RT and 2600ft of gain during the summer, all of it on trail. Consequently it is climbed frequently. Even in winter it sees many visitors. The entire area north of the peak is part of a large OSV (Over Snow Vehicles) winter playground, and it is not unusual to find snowmobiles at the summit in winter (in fact, probably 95% of winter visitiors on the summit arrive on snowmobiles). Without resorting to snowmobiles, a winter ascent is considerably more arduous - more than 20 miles RT over snow.",
        "Website": "https://www.summitpost.org/mount-lola/152684",
        "Image": "https://sp-images.summitpost.org/56379.jpg?auto=format&fit=max&h=800&ixlib=php-2.1.1&q=35&s=5d0c5abdad62ad130565bc710f51a606"
    },
    {
        "Peak Name": "Thor Peak",
        "Summit": "12,306 ",
        "Start": "8,300 ",
        "Mileage": "4.8",
        "Quad. Map": "Mount Whitney",
        "Class": "2",
        "Gain": "4,005 ",
        "Section": "4.8",
        "Trail Head": "Mount Whitney Trail",
        "Lat/Lon:": "36.57700°N / 118.265°W",
        "Overview": "Thor Peak is a spectacular sight from the Whitney Portal Road, often appearing much more impressive than its taller Sierra neighbors. Yet as a climb, it is overshadowed by nearby Whitney. However, it is a cool climb with some interesting routefinding and great views of the Whitney Region.",
        "Route": "It's class 2, but seems most people can't find the entire class 2 route on the way up and end up doing some class 3. Overall, there are a variety of established routes, from Class 1 walk-ups to 5.10 A2 routes and 5.10d free climbs.",
        "Website": "https://www.summitpost.org/thor-peak/151824",
        "Image": "https://sp-images.summitpost.org/911132.jpg?auto=format&fit=max&h=800&ixlib=php-2.1.1&q=35&s=21a656ae70241b8e135240957d0ee661"
    },
    {
        "Peak Name": "Lone Pine Peak",
        "Summit": "12,943 ",
        "Start": "7,860 ",
        "Mileage": "4.8",
        "Quad. Map": "Mount Langley",
        "Class": "2",
        "Gain": "5,085 ",
        "Section": "4.9",
        "Trail Head": "Meysan Lakes Trail",
        "Lat/Lon:": "36.56170°N / 118.224°W",
        "Overview": "This massive peak dominates the skyline west of Lone Pine. It appears larger and taller than Mts. Whitney, Russell and Langley, partly due to its bulk, and partly due to its location several miles east of the other other, much higher peaks. Though its summit does not quite reach 13,000 feet, it is nevertheless a very impressive mountain. ",
        "Route": "The summit offers magnificent views of the entire Mt. Whitney region, and is accessible to the average hiker willing to toil up a couple thousand feet of scree on the west side. Due to its proximity to Whiney Portal and the network of dirt roads along the desert's edge, Lone Pine Peak offers many opportunities to do a day climb at almost any level of difficulty one might desire. Those who are interested in a more relaxed pace will find plenty of campsites near lovely lakes and meadows in the Meysan Creek basin.",
        "Website": "https://www.summitpost.org/lone-pine-peak/150606",
        "Image": "https://sp-images.summitpost.org/183919.jpg?auto=format&fit=max&h=800&ixlib=php-2.1.1&q=35&s=2046495e1b4c2b1966d5a7990bee993b"
    },
    {
        "Peak Name": "Mount Johnson",
        "Summit": "12,871 ",
        "Start": "9,810 ",
        "Mileage": "5.0",
        "Quad. Map": "Mount Thompson",
        "Class": "2",
        "Gain": "3,360 ",
        "Loss": "300 ",
        "Section": "14.10",
        "Trail Head": "Bishop Pass Trail",
        "Lat/Lon:": "37.12800°N / 118.586°W",
        "Overview": "An SPS listed peak, Mt. Johnson (12,871') lies along the Sierra Crest southwest of Bishop, CA. Despite its short approach from the road (4 miles and 3,000' gain, one way), the peak is climbed relatively infrequently, and is seemingly sought after mostly by people working on the SPS List. But for the scrambler, Mt. Johnson is arguably the most desirable peak in the Bishop Pass area. It offers better scrambling than its neighbours, and the peak's northwest ridge in particular is a superb climb from Treasure Col, possibly one of the finest class 3 routes in the range.",
        "Route": "Northwest Ridge (class 3). The northwest ridge (called the north ridge by Secor) is somewhat unusual for a third class Sierra ridge route in that the spine of the ridge can be followed religiously from Treasure Col, with almost no variations from the ridge required to avoid obstacles. (I dropped off the spine in only one place, and even that was for only a few feet). The ridge features interesting scrambling, some exposure, some short knife edges, and generally excellent rock. It is a thoroughly enjoyable climb, and highly recommended.",
        "Website": "https://www.summitpost.org/mount-johnson/153424",
        "Image": "https://sp-images.summitpost.org/947233.jpg?auto=format&fit=max&h=800&ixlib=php-2.1.1&q=35&s=f0ab2eb333cb8545c27e90d1728b11a1"
    },
    {
        "Peak Name": "Mount Emerson",
        "Summit": "13,204 ",
        "Start": "9,250 ",
        "Mileage": "5.0",
        "Quad. Map": "Mount Darwin",
        "Class": "2",
        "Gain": "3,955 ",
        "Section": "16.2",
        "Trail Head": "Piute Pass Trail",
        "Lat/Lon:": "37.24200°N / 118.653°W",
        "Overview": "This is a relatively high and isolated mountain which commands an excellent view. The mountain was named by John Muir after writer Ralph Waldo Emerson! Mount Emerson is found between Piute Pass and Mount Humphreys. Its granite is in sharp contrast to the reddish rock of the Piute Crags.",
        "Route": "The North Face, a 1000' ice gully ( one of the 100 Classics of the High Sierra). The Southeast Face, an excellent class 5.4 rock climb. Very popular. The West Ridge - class 3 from Piute Pass. The South Face - class 3.",
        "Website": "https://www.summitpost.org/mount-emerson/151241",
        "Image": "https://sp-images.summitpost.org/436167.jpg?auto=format&fit=max&h=800&ixlib=php-2.1.1&q=35&s=c5b5a36534344dec5939dc5e71864e62"
    },
    {
        "Peak Name": "Cloudripper",
        "Summit": "13,525 ",
        "Start": "9,280 ",
        "Mileage": "5.0",
        "Quad. Map": "Mount Thompson",
        "Class": "2",
        "Gain": "4,295 ",
        "Loss": "50 ",
        "Section": "14.9",
        "Trail Head": "North Fork Trail",
        "Lat/Lon:": "37.14251°N / 118.53053°W",
        "Overview": "Cloudripper is the highest peak of the Inconsolable Range, a small subrange north of the Palisades and just outside Kings Canyon National Park in the Sierra Nevada. Rising to just over 13,500 feet, Cloudripper also ranks as the 58th highest in California and is included on the Sierra Club’s Sierra Peaks Section SPS List. One of the most accessible 13ers in California, there are several class 2 or 3 approach and route options, and trips to Cloudripper can be completed as moderate dayhikes involving as little as seven miles round trip and less than 4000 feet elevation gain. Overnight outings are popular as well, with multiple alpine lakes and meadows surrounding the peak in every direction.",
        "Route": "North slope from Green Lake - There are two variations that can be used. The shortest route heads due south from the south end of Green Lake, up the class 2 slopes of a headwall found at the south end of a meadow here. This route is somewhat steep and may have considerable snow in early season. A technically easier, but longer route continues on the trail up to the high plateau between Green Lake and Baker Creek. From the high plateau, head south along a broad, boulder strewn ridgeline, staying along the top. After a quarter mile the ridgeline curves to the right, though this isn't perceptable at first. The two routes converge on the north slope of Vagaabond Peak.",
        "Website": "https://www.summitpost.org/cloudripper/151202",
        "Image": "https://sp-images.summitpost.org/12026.jpg?auto=format&fit=max&h=800&ixlib=php-2.1.1&q=35&s=06b5e393c6b00df3b5903cc33bcdbc8a"
    },
    {
        "Peak Name": "Tunnabora Peak",
        "Summit": "13,563 ",
        "Start": "8,300 ",
        "Mileage": "5.0",
        "Quad. Map": "Mount Whitney",
        "Class": "2",
        "Gain": "5,365 ",
        "Loss": "300 ",
        "Section": "5.5",
        "Trail Head": "Mount Whitney Trail",
        "Lat/Lon:": "36.60510°N / 118.2813°W",
        "Overview": "Tunnabora Peak is located along the Sierra Crest, west of Lone Pine, CA. At 13,565 feet, the peak is overshadowed by its higher neighbours to the south, Mts. Russell, Whitney, and Muir. Tunnabora's relatively diminutive stature in comparison to these 14ers, in combination with what could charitably be described as less than classic climbing (some trip reports have given it the rather pejorative appellation of Tunnaboring), means the peak is infrequently climbed.",
        "Route": "The usual route up Tunnabora Peak is a fairly tedious slog up its sandy south slopes from Tulainyo Lake (class 1). Keeping to the left may offer marginally more solid footing, but don't expect a great climb whichever way you go. Another option is offered by a chute on the northwest face, which is class 2 from George Creek.",
        "Website": "https://www.summitpost.org/tunnabora-peak/151977",
        "Image": "https://sp-images.summitpost.org/134600.jpg?auto=format&fit=max&h=800&ixlib=php-2.1.1&q=35&s=eee497ca8387dfc9827a3ceec0df39d1"
    },
    {
        "Peak Name": "Cartago Peak",
        "Summit": "10,480+",
        "Start": "3,770 ",
        "Mileage": "5.0",
        "Quad. Map": "Olancha",
        "Class": "2s3",
        "Gain": "6,710 ",
        "Section": "3.2",
        "Trail Head": "West side of aquaduct",
        "Lat/Lon:": "36.32460°N / 118.1025°W",
        "Overview": "Cartago Peak is the informal name given to the highpoint of a series of granite pinnacles along the Sierra Crest, four miles west of the small town of Cartago. Given the peak's relative obscurity--it's unnamed, mentioned in no guide books, and isn't even marked with a spot elevation on USGS maps--it is climbed infrequently, only once or twice per year according to the register. However, the peak is an unusual and enjoyable scramble, and well worth a visit.",
        "Route": "Two routes have been described in trip reports. Cartago Peak is most commonly climbed from the Pacific Crest Trail (PCT) via Death Canyon, a roughly 31 mile round trip excursion out of Horseshoe Meadows. (If using this option, the peak is typically climbed in combination with Muah Mountain, the other SPS Listed peak in the immediate area). The other commonly used route approaches the peak from the east, literally from the town of Cartago. This is the shortest option, with round trip stats of only 9 miles and 6,700' gain, but despite the modest stats this approach is not to be underestimated--it begins in the desert at the 3,800' elevation, and involves slogging up seemingly endless steep, loose sand slopes.",
        "Website": "https://www.summitpost.org/cartago-peak/153339",
        "Image": "https://sp-images.summitpost.org/1052434.jpg?auto=format&fit=max&h=800&ixlib=php-2.1.1&q=35&s=2218b378cfc3e8548646e0bc7b8735c0"
    },
    {
        "Peak Name": "Mount Mills",
        "Summit": "13,451 ",
        "Start": "10,230 ",
        "Mileage": "5.1",
        "Quad. Map": "Mount Abbot",
        "Class": "3",
        "Gain": "3,320 ",
        "Loss": "100 ",
        "Section": "17.10",
        "Trail Head": "Mono Pass Trail",
        "Lat/Lon:": "37.39400°N / 118.79°W",
        "Overview": "Mt. Mills is one of many fine 13ers that surround the Little Lakes Valley, nestled between Ruby Peak and Mt. Abbot. There are a number of striking 13ers in the vicinity, and there are many traverses and enchainments available for the enthusiastic hiker/climber. In addition, there are a number of fantastic ski descents in the area, and it is a popular destination even in the winter.",
        "Route": "he approach to the east side of the peak is not far, just a little over 4 miles, half of it on a well-kept trail. For the north side routes, the approach is only a little longer, over Mono Pass, down into the Fourth Recess, past the Snow Lakes, and up a small glacier, for a total mileage of just over 6 miles, a very reasonable dayhike. ",
        "Website": "https://www.summitpost.org/mount-mills/151476",
        "Image": "https://sp-images.summitpost.org/53855.jpg?auto=format&fit=max&h=800&ixlib=php-2.1.1&q=35&s=a5b28345d60f2952cffa547c127afd10"
    },
    {
        "Peak Name": "Mount Rose",
        "Summit": "10,776 ",
        "Start": "8,820 ",
        "Mileage": "5.2",
        "Quad. Map": "Mount Rose",
        "Class": "1",
        "Gain": "1,955 ",
        "Section": "24.4",
        "Trail Head": "Mount  Rose Highway",
        "Lat/Lon:": "39.34318°N / 119.91622°W",
        "Overview": "Mount Rose is a gem in the northern Sierra Nevada Range. It rises only a few miles northeast of Lake Tahoe. It is the 2nd highest mountain in the Lake Tahoe Basin and the highest Tahoe Basin peak in Nevada. Standing over 6,300 feet above downtown Reno, the mountain looks daunting, however well-maintained trails starting high up a mountain pass road, cut most of the difficulty for the armchair hiker.  For this reason, if you hike the main trail, expect company, lots of company.  Not everybody hikes to the top of the mountain.  Many just go to the waterfall about 2 1/2 miles up the trail.  However, all of the Mount Rose Trail gets crowds all over, every weekend.",
        "Route": "From the Mount Rose Summit trailhead, there are two main approach routes, which follow the same trail for the last 2.3 miles. The last 2.3 miles is where the last 1700 feet of elevation is gained.",
        "Website": "https://www.summitpost.org/mount-rose-nevada/150662",
        "Image": "https://sp-images.summitpost.org/76604.jpg?auto=format&fit=max&h=800&ixlib=php-2.1.1&q=35&s=348ef46f39459782a66ad045c7e444a2"
    },
    {
        "Peak Name": "Mount Dade",
        "Summit": "13,600+",
        "Start": "10,230 ",
        "Mileage": "5.3",
        "Quad. Map": "Mount Abbot",
        "Class": "2",
        "Gain": "3,470 ",
        "Loss": "100 ",
        "Section": "17.8",
        "Trail Head": "Mono Pass Trail",
        "Lat/Lon:": "37.38170°N / 118.7783°W",
        "Overview": "Mount Dade is one of the high peaks in the Mount Abbot Group, on the Sierra crest between Mount Abbot and Bear Creek Spire, at the head of Rock Creek Canyon. The Little Lakes Valley at the head of the canyon is is one of the most picturesque regions of the Sierra Nevada, yet it is relatively easy to reach. The high summer trailhead at Mosquito Flat (10,300 feet) offers short approach routes to these magnificent peaks.",
        "Route": "Fortunately, Mount Dade is one of the easiest peaks in this area, offering a challenging but doable class 2 route up its south slope. This route involves climbing the famous Hourglass Couloir which can be choked with ice even in late summer. Mount Dade is also a popular winter mountaineering peak, with excellent skiing terrain from the very top down its moderate south slopes, followed by the 1,000 foot, 40 degree slope of the Hourglass.",
        "Website": "https://www.summitpost.org/mount-dade/150604",
        "Image": "https://sp-images.summitpost.org/715821.JPG?auto=format&fit=max&h=800&ixlib=php-2.1.1&q=35&s=12a0ffd797336806aa1e4be524c94027"
    },
    {
        "Peak Name": "MOUNT ABBOT",
        "Summit": "13,704 ",
        "Start": "10,230 ",
        "Mileage": "5.3",
        "Quad. Map": "MOUNT ABBOT",
        "Class": "3",
        "Gain": "3,575 ",
        "Loss": "100 ",
        "Section": "17.9",
        "Trail Head": "Mono Pass Trail",
        "Lat/Lon:": "37.38610°N / 118.7833°W",
        "Overview": "Mount Abbot is the central peak in the Abbot Group of Sierra Nevada peaks, six of which have elevations of 13400-13800 ft. It sits on the Sierra crestline flanked by Mount Mills on the northwest, Bear Creek Spire and Mount Dade on the southeast, its southwest side connects with Mount Gabb on the Mono Divide, its northeast side faces bulky Mount Morgan. This region features dramatic vertical relief of steep walls and buttresses surrounding the high summits, offering challenging rock, snow, and ice climbing.",
        "Route": "Mount Abbot itself is not the hardest peak in the area, with its NE couloir route rated class 3. Climber must first overcome a 1000 foot high snow couloir (no bergschrund) with an average slope of 40 degrees before reaching class 3 rock. Depending on snow/ice conditions, ice axe and/or crampons may be required.",
        "Website": "https://www.summitpost.org/mount-abbot/150485",
        "Image": "https://sp-images.summitpost.org/1034673.png?auto=format&fit=max&h=800&ixlib=php-2.1.1&q=35&s=93417b8e8d77e3ec95be62275d03986e"
    },
    {
        "Peak Name": "Mount Morgan (S)",
        "Summit": "13,748 ",
        "Start": "9,710 ",
        "Mileage": "5.3",
        "Quad. Map": "Mount Morgan",
        "Class": "2",
        "Gain": "4,340 ",
        "Loss": "300 ",
        "Section": "17.11",
        "Trail Head": "Tamarack Lakes Trail",
        "Lat/Lon:": "37.40570°N / 118.733°W",
        "Overview": "Mount Morgan 13,748' is located in the Rock Creek region of the Eastern Sierra Nevada Mountains. It is the 31st highest peak in California and the highest in the Rock Creek area.  It is often referred to as Mount Morgan (S) because another Mount Morgan is located less than 8 miles north at an elevation of 13,001'.",
        "Route": "The easiest route on Mount Morgan is the Tamarack lakes trailhead to Francis Lake then the obvious ridge to the peak. The views are truly excellent from this peak. Mount Morgan is on the Sierra Peaks List.",
        "Website": "https://www.summitpost.org/mount-morgan-s/151316",
        "Image": "https://sp-images.summitpost.org/715815.jpg?auto=format&fit=max&h=800&ixlib=php-2.1.1&q=35&s=5fd5151714b9ba4aade269b47d3b148b"
    },
    {
        "Peak Name": "Freel Peak",
        "Summit": "10,881 ",
        "Start": "7,840 ",
        "Mileage": "5.4",
        "Quad. Map": "Freel Peak",
        "Class": "1",
        "Gain": "3,050 ",
        "Section": "23.8",
        "Trail Head": "Fountain Place",
        "Lat/Lon:": "38.85690°N / 119.9002°W",
        "Overview": "Many peaks ring Lake Tahoe in Northern California, but none rise higher than Freel Peak. Located at the southern end of the Carson Range, which runs north to south along the east side of Lake Tahoe, Freel Peak is the highest point in the Carson Range, the Lake Tahoe Basin and El Dorado County.",
        "Route": "There are many ways to reach the top of Freel Peak. The well-rounded summit may be reached class 1 from all sides. The peak is covered in sand making is a slog to get up. Another concern is the rare and delicate Tahoe Draba lives on the slops of Freel Peak.",
        "Website": "https://www.summitpost.org/freel-peak/151340",
        "Image": "https://sp-images.summitpost.org/27097.JPG?auto=format&fit=max&h=800&ixlib=php-2.1.1&q=35&s=cfa9dcecbfdb9ccffc3eba79a1ca0d8d"
    },
    {
        "Peak Name": "Mount Gilbert",
        "Summit": "13,106 ",
        "Start": "9,810 ",
        "Mileage": "5.5",
        "Quad. Map": "Mount Thompson",
        "Class": "2",
        "Gain": "3,675 ",
        "Loss": "380 ",
        "Section": "14.11",
        "Trail Head": "Bishop Pass Trail",
        "Lat/Lon:": "37.13700°N / 118.597°W",
        "Overview": "Mt. Gilbert features one of the finest ice climbs in the High Sierra, the excellent North Couloir route. This 900', 65 degree ice gully is visable from the parking lot at South Lake. The climb is rated III, 5.6, AI2 or WI3. For the High Sierra ice climber, this is a \" must do \" classic climb of the range!",
        "Route": "Other routes include - The Southeast Slope - class 1 or The East Ridge - class 2 via a loose chute from above the Treasure Lakes.",
        "Website": "https://www.summitpost.org/mount-gilbert/151224",
        "Image": "https://sp-images.summitpost.org/142405.jpg?auto=format&fit=max&h=800&ixlib=php-2.1.1&q=35&s=a3b795031265eabbb59756b71ca7df9d"
    },
    {
        "Peak Name": "Temple Crag",
        "Summit": "12,976 ",
        "Start": "7,800 ",
        "Mileage": "5.5",
        "Quad. Map": "Split Mountain",
        "Class": "3",
        "Gain": "5,475 ",
        "Loss": "300 ",
        "Section": "14.1",
        "Trail Head": "South Fork Trail",
        "Lat/Lon:": "37.10970°N / 118.4917°W",
        "Overview": "Temple Crag is home to one of the longest routes in the Sierras. Most of Temple Crag's routes are grade III or more. All routes will excite the soul and light the imagination. Wild exposure on towering gendarmes and striking aretes are the highlights.",
        "Route": "ecommended routes: Moon Goddess Arete (III 5.7), Sun Ribbon Arete (IV 5.9....which features a Tyrolean traverse, Dark Star (V 5.10 A0).....all five star routes. Get an early start on Sun Ribbon Arete (20 pitches) and Dark Star (26 pitches)!!",
        "Website": "https://www.summitpost.org/temple-crag/150844",
        "Image": "https://sp-images.summitpost.org/470721.JPG?auto=format&fit=max&h=800&ixlib=php-2.1.1&q=35&s=f07d01092c01ff3775d54fd3ee3c1d6e"
    },
    {
        "Peak Name": "Mount Lamarck",
        "Summit": "13,417 ",
        "Start": "9,260 ",
        "Mileage": "5.6",
        "Quad. Map": "Mount Darwin",
        "Class": "1",
        "Gain": "4,155 ",
        "Section": "15.9",
        "Trail Head": "Lamark Lakes Trail",
        "Lat/Lon:": "37.19500°N / 118.67°W",
        "Overview": "Mount Lamarck lies on the crest of the High Sierra about 1 1/2 miles north of Mount Darwin. While easily climbed from the cross country trail over Lamarck Col ( class 2 ), Mount Lamarck also has a moderate ice gully on the North Face which provides excellent snow and ice climbing. The South Slope and Southeast Slope are also class 2.",
        "Route": "Take the Lamarck Lakes trail to Upper Lamarck Lake, then continue on the use trail to Lamarck Col. Scramble up the easy class 2 left (west) side of the ridge, over insignificant Mt. Lamarck, and on to the summit of the ridge.",
        "Website": "https://www.summitpost.org/mount-lamarck/151232",
        "Image": "https://sp-images.summitpost.org/215630.jpg?auto=format&fit=max&h=800&ixlib=php-2.1.1&q=35&s=5855d36b25b0777ec2e2bb7da72770e8"
    },
    {
        "Peak Name": "Bloody Mountain",
        "Summit": "12,552 ",
        "Start": "7,300 ",
        "Mileage": "5.6",
        "Quad. Map": "Bloody Mountain",
        "Class": "2",
        "Gain": "5,250 ",
        "Section": "18.9",
        "Trail Head": "Laurel Creek Trail",
        "Lat/Lon:": "37.56050°N / 118.907°W",
        "Overview": "Bloody Mountain stands out as a beautiful red peak approximately 1 mile north of Mt Morrison as you cruise the 395 in the Mammoth Lakes area. It also lies southwest of nearby Laurel Mountain and the two can be easily combined for a nice dayhike loop. A narrow snow couloir culminating in a prominent \"Y\" shaped rock rib just below the saddle stands out against the contrasting white bed of background snow in springtime, drawing just about everyone to gawk and think \"gee, that looks like fun...\"",
        "Route": "This has long been a dayhike destination for backcountry skiers and snowboarders as well due to the relatively short approach and fun steep lines back down to the bottom. Depending on the route and season you choose you can look forward to lines ranging from hellish talus and scree slogs to fun season opener snow climbs.",
        "Website": "https://www.summitpost.org/bloody-mountain/152659",
        "Image": "https://sp-images.summitpost.org/98232.jpg?auto=format&fit=max&h=800&ixlib=php-2.1.1&q=35&s=1f40b819369daa0f43ca7025472f0ba3"
    },
    {
        "Peak Name": "Rockhouse Peak",
        "Summit": "8,360+",
        "Start": "5,845 ",
        "Mileage": "5.7",
        "Quad. Map": "Rockhouse Basin",
        "Class": "2",
        "Gain": "3,035 ",
        "Loss": "520 ",
        "Section": "1.6",
        "Trail Head": "Rockhouse Basin Trail",
        "Lat/Lon:": "35.90100°N / 118.2287°W",
        "Overview": "Rockhouse Peak (Peak 8360+) is a prominent dome located approximately in the center of the Southern Sierra's Domeland Wilderness, a beautiful area of granite domes, spires, and outcroppings set amongst streams and expansive meadows. As one might expect given this location, it commands superb views over the Dome Land's granite expanses, with panoramas extending beyond the surrounding wilderness to Olancha Peak to the north and towards Spanish Needle and Owens Peak to the south. In fact, the view west from the summit is used as the cover photo for the USFS Domeland Wilderness map.",
        "Route": "The usual route up the peak climbs the class 3 East Face, a short, easy, but enjoyable scramble. A talus-and-slab weakness in the North Face is described as class 2. The South Face presents some short technical climbs: a 2-pitch 5.7 route named \"Immaculate Conception\" for the clean rock, and a 1-pitch class 5 trough. There is much steep--even overhanging--rock on the South and West Faces, and scramble routes (class 4 or less) on these sides of the peak appear to be non-existent.",
        "Website": "https://www.summitpost.org/rockhouse-peak/152727",
        "Image": "https://sp-images.summitpost.org/1052096.jpeg?auto=format&fit=max&h=800&ixlib=php-2.1.1&q=35&s=c52bec8bddbab262cfafa0bf14c92c36"
    },
    {
        "Peak Name": "Granite Chief",
        "Summit": "9,006 ",
        "Start": "6,245 ",
        "Mileage": "5.7",
        "Quad. Map": "Granite Chief",
        "Class": "1",
        "Gain": "3,380 ",
        "Loss": "620 ",
        "Section": "24.1",
        "Trail Head": "Squaw Valley Fire Station",
        "Lat/Lon:": "39.19800°N / 120.286°W",
        "Overview": "Granite Chief is located on the northeast edge of the same named 25,680 acre Granite Chief Wilderness near the west rim of the Tahoe Basin. It is also located just west of the Squaw Valley USA ski area, home of the 1960 Winter Olympics . There are usually two reasons for seeking the summit of Granite Chief, the peak has spectacular views in all directions and it is the target of county high pointers since it was the high point of Placer County until a new liner point was discovered in 2008 on the Placer County - Washoe County line. Granite Chief stands out as its light granite composition contrasts with the darker volcanic rock of the nearby peaks. ",
        "Route": "The hike up is very enjoyable as it passes through some nicely wooded forests (including a University of California Ecology Study Area) as well as across open granite hillsides and through some pleasant meadows. The trail skirts along the north edge of the ski area and along a segment of the Pacific Crest Trail. This leads to the only drawback on the hike in that you almost always have the lifts of the Squaw Valley in view and are not far from civilization. The final segment of the hike passes under a ski lift and then you head for the summit from the upper lift shed. In fact if one were so inclined, a good segment of the hike can be cut off by using the gondola to Squaw’s High Camp area at 8200 ft.",
        "Website": "https://www.summitpost.org/granite-chief/152880",
        "Image": "https://sp-images.summitpost.org/74261.JPG?auto=format&fit=max&h=800&ixlib=php-2.1.1&q=35&s=40616eef2778ef8e98627d0a941dd8d2"
    },
    {
        "Peak Name": "Mount Bradley",
        "Summit": "13,264 ",
        "Start": "5,880 ",
        "Mileage": "5.7",
        "Quad. Map": "Mount Williamson",
        "Class": "2",
        "Gain": "7,825 ",
        "Loss": "480 ",
        "Section": "8.10",
        "Trail Head": "Pinyon Creek Trail",
        "Lat/Lon:": "36.72855°N / 118.33864°W",
        "Overview": "Fine looking peak that sees relatively few visitors. Fantastic views from the summit of Mount Keith, Junction Peak, Mount Willamson, and Mount Tyndall to the South, University Peak to the North and the High Sierra of Kings Canyon and Sequoia National Parks as well as the Center Basin to the West.",
        "Route": "The main trailhead is the Onion Valley Trailhead, which can be reached by driving 13 miles west on the Onion Valley Road from Independence until the road ends. From the Onion Valley trailhead take the Robinson Lakes Trailhead. This is the most direct approach to the Center Basin and leads over University Pass at 12,640 feet. From Robinson Lake, head west up the creek and aim at the lowest point between University Peak (to the North) and the unnamed peak 12,910 (to the South). A steep gully that is often filled with snow until later in the summer leads up to University Pass. Now head South and try to stay as high up on the slopes as feels comfortable in order to avoid elevation loss. Pass the Center Basin Crags and head up the talus chute that leads directly up to saddle between the two summits of Bradley (Class 2). The northern summit is the high point.",
        "Website": "https://www.summitpost.org/mount-bradley/208629",
        "Image": "https://sp-images.summitpost.org/844146.jpg?auto=format&fit=max&h=800&ixlib=php-2.1.1&q=35&s=00daeac771599ae346d1fb1b07dab0dc"
    },
    {
        "Peak Name": "Leavitt Peak",
        "Summit": "11,569 ",
        "Start": "9,620 ",
        "Mileage": "5.8",
        "Quad. Map": "Sonora Pass",
        "Class": "1",
        "Gain": "2,400 ",
        "Loss": "450 ",
        "Section": "23.2",
        "Trail Head": "Pacific Crest Trail",
        "Lat/Lon:": "38.28597°N / 119.6511°W",
        "Overview": "Leavitt Peak is a broad rounded peak located near Sonora Pass on California State Route 108, one of the 3 trans-Sierra routes closed during the winter. There are several peaks in the area that can be summited in a day or less, but Leavitt is the highest. It is located south of the pass in the Emigrant Wilderness and is a nice side trip for those traveling the Pacific Crest Trail. Leavitt offers views south towards Yosemite and North towards the South Tahoe high country. Summer weekends can be a busy time in this area with quite a few people making the summit",
        "Route": "The northeast ridge is a straightforward class 2 scramble that gets a little knife edgy in places. It is a satisfying alternative to the regular route for those looking for a more interesting approach.  It is a little shorter.  It is recommended that hikers descend via the east shoulder.",
        "Website": "https://www.summitpost.org/leavitt-peak/150498",
        "Image": "https://sp-images.summitpost.org/401403.JPG?auto=format&fit=max&h=800&ixlib=php-2.1.1&q=35&s=68a0eb769b6acf6e62d7a788d4c12b12"
    }
]